import type { MindMapData } from "../types";

/**
 * 产品研发流程示例（与 Story「WithInitialData」一致），便于单独维护。
 */
export const RD_PROCESS_INITIAL_DATA: MindMapData = {
  rootId: "root",
  nodes: {
    root: {
      id: "root",
      text: "产品研发流程",
      parentId: null,
      children: ["inspire", "req", "design", "proto", "tech", "ops"],
      isExpanded: true,
      depth: 0,
    },
    inspire: {
      id: "inspire",
      text: "灵感",
      parentId: "root",
      children: ["brainstorm"],
      isExpanded: true,
    },
    brainstorm: {
      id: "brainstorm",
      text: "头脑风暴",
      parentId: "inspire",
      children: [],
      isExpanded: true,
    },
    req: {
      id: "req",
      text: "需求",
      parentId: "root",
      children: ["feas", "core-req"],
      isExpanded: true,
    },
    feas: {
      id: "feas",
      text: "可行性分析",
      parentId: "req",
      children: ["feas-doc"],
      isExpanded: true,
    },
    "feas-doc": {
      id: "feas-doc",
      text: "需求分析：可行性研究报告",
      parentId: "feas",
      children: [],
      isExpanded: true,
    },
    "core-req": {
      id: "core-req",
      text: "核心需求分析",
      parentId: "req",
      children: ["core-doc"],
      isExpanded: true,
    },
    "core-doc": {
      id: "core-doc",
      text: "产出：产品核心需求文档",
      parentId: "core-req",
      children: [],
      isExpanded: true,
    },
    design: {
      id: "design",
      text: "方案设计",
      parentId: "root",
      children: ["design-detail", "ui-draft", "effort", "demo"],
      isExpanded: true,
    },
    "design-detail": {
      id: "design-detail",
      text: "方案设计",
      parentId: "design",
      children: ["out-prd", "out-uiux"],
      isExpanded: true,
    },
    "out-prd": {
      id: "out-prd",
      text: "产出详细的 PRD",
      parentId: "design-detail",
      children: [],
      isExpanded: true,
    },
    "out-uiux": {
      id: "out-uiux",
      text: "产出详细的 UI/UX 高保真交互设计文档",
      parentId: "design-detail",
      children: [],
      isExpanded: true,
    },
    "ui-draft": {
      id: "ui-draft",
      text: "UI设计稿",
      parentId: "design",
      children: [],
      isExpanded: true,
    },
    effort: {
      id: "effort",
      text: "工作量评估",
      parentId: "design",
      children: [],
      isExpanded: true,
    },
    demo: {
      id: "demo",
      text: "案例演示",
      parentId: "design",
      children: [],
      isExpanded: true,
    },
    proto: {
      id: "proto",
      text: "原型",
      parentId: "root",
      children: ["sys-proto"],
      isExpanded: true,
    },
    "sys-proto": {
      id: "sys-proto",
      text: "系统原型",
      parentId: "proto",
      children: [],
      isExpanded: true,
    },
    tech: {
      id: "tech",
      text: "技术实现",
      parentId: "root",
      children: ["plan", "abstract", "analyze-prob", "test"],
      isExpanded: true,
    },
    plan: {
      id: "plan",
      text: "规划",
      parentId: "tech",
      children: ["plan-file", "plan-data"],
      isExpanded: true,
    },
    "plan-file": {
      id: "plan-file",
      text: "文件结构路径规划",
      parentId: "plan",
      children: [],
      isExpanded: true,
    },
    "plan-data": {
      id: "plan-data",
      text: "数据模型的设计",
      parentId: "plan",
      children: [],
      isExpanded: true,
    },
    abstract: {
      id: "abstract",
      text: "抽象",
      parentId: "tech",
      children: [],
      isExpanded: true,
    },
    "analyze-prob": {
      id: "analyze-prob",
      text: "分析问题",
      parentId: "tech",
      children: [],
      isExpanded: true,
    },
    test: {
      id: "test",
      text: "测试",
      parentId: "tech",
      children: ["iface-test"],
      isExpanded: true,
    },
    "iface-test": {
      id: "iface-test",
      text: "接口测试: interface-testing",
      parentId: "test",
      children: ["test-case", "ai-test"],
      isExpanded: true,
    },
    "test-case": {
      id: "test-case",
      text: "1, 设计场景测试用例",
      parentId: "iface-test",
      children: [],
      isExpanded: true,
    },
    "ai-test": {
      id: "ai-test",
      text: "2. AI测试+人工确认",
      parentId: "iface-test",
      children: [],
      isExpanded: true,
    },
    ops: {
      id: "ops",
      text: "技术运维",
      parentId: "root",
      children: [],
      isExpanded: true,
    },
  },
};
